services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: mani
      POSTGRES_PASSWORD: mani
      POSTGRES_DB: short_term_memory_db
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"